[package]
name = "gaiku-common"
version = "0.1.0"
authors = ["Norman Paniagua <normanpaniagua@gmail.com>"]
edition = "2018"

[dependencies]
decorum = "0.1.3"
derive_builder = "0.7.1"
derive-new = "0.5.6"
getset = "0.0.7"
nalgebra = "0.17.3"
num-traits = "0.2.6"
