name:                   Bench

on:
  pull_request:
    branches:           [ master ]

env:
  CARGO_TERM_COLOR:     always

jobs:
  bench:

    runs-on:            ubuntu-latest

    steps:
      - name:           Install dependencies
        run:            |
          sudo apt update
          sudo apt-get install -y gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev pulseaudio
      - name:           Install latest nightly
        uses:           actions-rs/toolchain@v1
        with:
            toolchain:  nightly
            components: cargo

      - name:           Checkout
        uses:           actions/checkout@v2
        with:
          ref:          ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      # Bench on the base of this PR
      - name:           Checkout Base
        run: |
          git branch ${{ github.base_ref }} origin/${{ github.base_ref }}
      - name:           Bench Base
        uses:           actions-rs/cargo@v1
        with:
          command:      bench
          toolchain:    nightly
          args:         --all-features --all
      # Bench on the last commit of this PR
      - name:           Checkout PR
        run: |
          git branch ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.head.sha }}
      - name:           Bench PR
        uses:           actions-rs/cargo@v1
        with:
          command:      bench
          toolchain:    nightly
          args:         --all-features --all
      - name:           Export Reports
        uses:           actions/upload-artifact@v2
        with:
          name:         Reports
          path:         "target/criterion"
