name:                Bench

on:
  pull_request:
    branches:        [ master ]

env:
  CARGO_TERM_COLOR:  always

jobs:
  build:

    runs-on:         ubuntu-latest

    steps:
      - name:        Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev pulseaudio
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: cargo

      # Check out the base of this PR
      - name:        Checkout
        uses:        actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      # Bench on base of the PR
      - name:        Bench
        uses:        actions-rs/cargo@v1
        with:
          command: bench
          toolchain: nightly
          args:    --verbose --all-features --all
      # Check out the last commit of this PR
      - name:        Checkout
        uses:        actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # Bench on the last commit of this PR
      - name:        Bench
        uses:        actions-rs/cargo@v1
        with:
          command: bench
          toolchain: nightly
          args:    --verbose --all-features --all
